# Generated by Django 4.2 on 2023-06-26 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='professor',
            options={'ordering': ('name', 'persnr'), 'verbose_name': 'Professor', 'verbose_name_plural': 'Professoren'},
        ),
    ]
