# Generated by Django 4.2 on 2023-06-26 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0002_alter_professor_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('name', 'matnr'), 'verbose_name': 'Student', 'verbose_name_plural': 'Studenten'},
        ),
        migrations.AlterModelOptions(
            name='vorlesung',
            options={'ordering': ('titel', 'vorlnr'), 'verbose_name': 'Vorlesung', 'verbose_name_plural': 'Vorlesungen'},
        ),
    ]
