# Generated by Django 4.2 on 2023-07-03 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('university', '0003_alter_student_options_alter_vorlesung_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pruefung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datum', models.DateField()),
                ('note', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='university.student')),
                ('vorlesung', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='university.vorlesung')),
            ],
            options={
                'verbose_name': 'Pruefung',
                'verbose_name_plural': 'Pruefungen',
                'ordering': ('student', 'vorlesung', 'note', 'datum'),
            },
        ),
    ]
